// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package backend


import scala.concurrent.Future


trait WeatherWebServiceSoap {
  def getSupportCity(byProvinceName: Option[String]): Future[backend.GetSupportCityResponse]
  def getSupportProvince(): Future[backend.GetSupportProvinceResponse]
  def getSupportDataSet(): Future[backend.GetSupportDataSetResponse]
  def getWeatherbyCityName(theCityName: Option[String]): Future[backend.GetWeatherbyCityNameResponse]
  def getWeatherbyCityNamePro(theCityName: Option[String], theUserID: Option[String]): Future[backend.GetWeatherbyCityNameProResponse]
}




